trigger:
  paths:
    include:
      - apps/web
      - packages

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: fix/acr-push-artifact-name-2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: apps/web/pipelines/azure-pipelines-variables.yml@self
    validateName: Build
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - template: steps/azure_web_app_acr_push.yml@templates
        parameters:
          azurecrName: $(azurecrName)
          dockerfilePath: $(dockerFilePath)
          repository: $(repository)
          runTests: false
          workingDirectory: $(Build.Repository.LocalPath)
