parameters:
  - name: deploymentTag
    displayName: Deployment Tag
    type: string
    default: none
  - name: region
    displayName: Region
    type: string
    values:
      - UK West
      - UK South
    default: UK West

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.1.0
  pipelines:
    - pipeline: back-office-web-build
      source: Back Office Web Build
      trigger:
        branches:
          include:
            - develop

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Deploy
        deploymentSteps:
          - script: |
              buildName=$(versionNumber)_$(Build.BuildId)
              echo "Setting the name of the build to '$buildName'."
              echo "##vso[build.updatebuildnumber]$buildName"
            displayName: Set Build Number
          - template: ../steps/azure_web_app_deploy.yml
            parameters:
              appName: $(webAppName)
              appResourceGroup: $(resourceGroup)
              azurecrName: $(azurecrName)
              repository: $(repository)
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: apps/web/pipelines/azure-pipelines-variables.yml@self
